### ISSUE TITLE
[Week 5] Project: v1.0 Milestones

### ISSUE THREAD

**Issue by QzSG** [CS2113-AY1819S1-T13-1/main#15]
> Files can be edit at the [Wiki](https://github.com/CS2113-AY1819S1-T13-1/main/wiki)

## v1.0 Documentation
Developer Guide: Have a draft of the requirements of your project, as described in mid-v1.0 progress guide.

- [x] [Draft User Guide](https://github.com/CS2113-AY1819S1-T13-1/main/wiki/Draft-User-Guide)
I have made some refactoring and edits to the AB4 User guide
Kindly do review / edit / add on

- [x] [Draft Developer Guide](https://github.com/CS2113-AY1819S1-T13-1/main/wiki/Draft-Developer-Guide)
I have modified user stories a bit. Kindly do review / edit / add on.
 
- [x] Project Management : 
  1. [x] Feature Allocation 
  2. [x] Feature Release Schedule

**Comment by QzSG** [comment]
@ChenSongJian @luhan02 @ian-tjahjono @T0roloco Not sure if you guys receive notifications about this, but do `Watch` (top right beside `Star` repo ) this repo if u don't.
