### ISSUE TITLE
[Feature] Backup Student Planner Data

### ISSUE THREAD

**Issue by QzSG** [CS2113-AY1819S1-T13-1/main#35]
User story #3 

#### Tasks
- [x] Add Backup Command
- [x] Add Backup API to Storage Component
- [x] Add Backup API to Model Component
- [x] Add Backup Request Event
- [x] Working Default Backup Command
- [x] Unit Tests
