### ISSUE TITLE
[Feature] Backup Student Planner Data v1.2

### ISSUE THREAD

**Issue by QzSG** [CS2113-AY1819S1-T13-1/main#38]
User story #3 

Extension of #35 

#### Tasks
- [x] Make backup function more generic to allow for future extensions
- [x] Creation of BackupCommandParser in anticipation of online backups
- [x] Create a generic online service backup driver so its easy to extend different backup services
- [x] Look into restoration of data
- [x] Unit Tests
- [x] Look into relevant UI for user feedback.
