### ISSUE TITLE
Feedback on week 9 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [CS2113-AY1819S1-T13-1/main#69]
Subject: feedback on week 9 project progress

See [v1.2 progress guide](https://nuscs2113-ay1819s1.github.io/website/admin/project-w09-v12.html) for more details of the activities mentioned below.

### Recommended progress for v1.2

- [x]  Issue labels set up e.g., `type.*`, `priority.*` (:heavy_check_mark: well done!)
- [x]  Milestones created: v1.2 v1.4 v1.3 [Please ensure milestones are setup until 'v1.4'] (:heavy_check_mark: well done!)
- [x]  Some issues marked as `type.Story` e.g., [link](https://github.com/CS2113-AY1819S1-T13-1/main/issues/1) (:heavy_check_mark: well done!)
- [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/CS2113-AY1819S1-T13-1/main/issues/15) (:heavy_check_mark: well done!)
*  Milestone v1.2 _managed_ systematically
   -  [ ]  A suitable deadline set (:exclamation: try to do by next milestone)
   -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/CS2113-AY1819S1-T13-1/main/issues/19) (:heavy_check_mark: well done!)
   -  [x]  All issues/PRs in it are closed/merged. (:heavy_check_mark: well done!)
   -  [x]  Milestone closed  (:heavy_check_mark: well done!)
   -  [x]  Code tagged as `v1.2`  (:heavy_check_mark: well done!)
- [x]  Build passing (:heavy_check_mark: well done!)
-  [x]  Some issues assigned to milestone v1.3 e.g., [link](https://github.com/CS2113-AY1819S1-T13-1/main/issues/3) (:heavy_check_mark: well done!)

Not graded:
- [x] Updated User Guide for v1.2  (:+1:  Kudos!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for v1.2 milestone (:heavy_check_mark: well done!)

### Leftovers from v1.1

* Used forking workflow:
   - [x]  Forked team repo (:heavy_check_mark: well done!)
   - [x]  Created PRs [link](https://github.com/CS2113-AY1819S1-T13-1/main/pull/41) (:heavy_check_mark: well done!)
   - [x]  Gave review comments to other PRs (:heavy_check_mark: well done!)
- [ ]  Merged updates to documents (:exclamation: try to do by next milestone)
- [x]  `chensongjian.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [x]  Has issues/PRs assigned for v1.2 milestone (:heavy_check_mark: well done!)

### Leftovers from v1.1

* Used forking workflow:
   - [x]  Forked team repo (:heavy_check_mark: well done!)
   - [x]  Created PRs [link](https://github.com/CS2113-AY1819S1-T13-1/main/pull/52) (:heavy_check_mark: well done!)
   - [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)
- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `t0roloco.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [x]  Has issues/PRs assigned for v1.2 milestone (:heavy_check_mark: well done!)

### Leftovers from v1.1

* Used forking workflow:
   - [x]  Forked team repo (:heavy_check_mark: well done!)
   - [x]  Created PRs [link](https://github.com/CS2113-AY1819S1-T13-1/main/pull/49) (:heavy_check_mark: well done!)
   - [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)
- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `ian-tjahjono.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for v1.2 milestone (:heavy_check_mark: well done!)

### Leftovers from v1.1

* Used forking workflow:
   - [x]  Forked team repo (:heavy_check_mark: well done!)
   - [x]  Created PRs [link](https://github.com/CS2113-AY1819S1-T13-1/main/pull/44) (:heavy_check_mark: well done!)
   - [ ]  Gave review comments to other PRs (:exclamation: try to do by next milestone)
- [x]  Merged updates to documents (:heavy_check_mark: well done!)
- [x]  `luhan02.png` uploaded and linked from AboutUs page in png format (change image to png if presently in different format) (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for v1.2 milestone (:heavy_check_mark: well done!)

Tutor: @ewaldhew

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2018-10-18 02:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.

**Comment by QzSG** [comment]
@cs2113-feedback-bot 

> A suitable deadline set (❗️ try to do by next milestone)

Deadline was set to tutorial date as mentioned in lecture, and properly closed too. Not detected? (I have since changed back to the date before the tutorial (which was accepted in mid v1.2))

**Comment by nus-pe-script** [comment]
Hi,

As per our records, your v1.2 milestone due date was set to be: 2018-10-18 07:00:00 , whereas it should have been earlier than 2018-10-18 02:00:00 .

However, as you have closed the milestone within time (milestone closed has been ticked and noted), you may choose to ignore this deadline detail. In other words, "closing the milestone" deems the "suitable deadline" field irrelevant.

Hope this clarifies your doubts. Please feel free to comment on this thread if required.

Regards,
CS2113-feedback-bot-team

**Comment by QzSG** [comment]
@cs2113-feedback-bot 

> As per our records, your v1.2 milestone due date was set to be: 2018-10-18 07:00:00 , whereas it should have been earlier than 2018-10-18 02:00:00 

Using GitHub UI only allows setting for Date , while Time can only be modified if I manually access the graphql api or v3 rest api if I am not mistaken. Perhaps we should be advised to set our milestone deadlines to be the day before our tutorials instead of "or the day of our tutorials" as mentioned during lecture? Thanks!
